### PR TITLE
Brought tests internal to the repo

### PR DESCRIPTION
**Pull request by tvincentNuoDB**
For support past Django 1.5 we will need the tests to be internal to the repo as they are not bundled in the Django install.

Cleaned up the travis build script.

Updated the test running script

### CODE REVIEW

**Comment by tvincentNuoDB** [comment]
As shown [here](https://docs.djangoproject.com/en/1.8/releases/1.6/#discovery-of-tests-in-any-test-module), versions of django starting with 1.6 search the project directory for unittests

**Comment by VDuda** [comment]
Why do you ignore "from django.test.testcases import skipIfDBFeature" ? Also could you clean up the django_tests.sh script a bit? Don't really think we need some of those comments + ls statements

**Comment by tvincentNuoDB** [comment]
Whoops, part of the old test script, I found out the test it skips doesn't actually need to be skipped. Removed this and a few finder tmp files.

I would like to keep the comments for future improvements (so it doesn't fall into the state it was in before). You may be looking at an outdated diff with the ls.

**Comment by VDuda** [comment]
Ok! Going to merge squash to preserve clean commit history.

**Pull request closed without merging**
